# Generated by Django 3.0.5 on 2020-04-14 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.PositiveSmallIntegerField(null=True)),
                ('courseID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=31)),
                ('units', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sp', models.BooleanField()),
                ('Max', models.PositiveSmallIntegerField()),
                ('enr', models.PositiveSmallIntegerField()),
                ('avl', models.SmallIntegerField()),
                ('wl', models.PositiveSmallIntegerField()),
                ('gm', models.CharField(max_length=2)),
                ('yl', models.BooleanField()),
                ('pr', models.BooleanField()),
                ('fr', models.BooleanField()),
                ('la', models.BooleanField()),
                ('qa', models.BooleanField()),
                ('Format', models.CharField(max_length=3)),
                ('xlist', models.CharField(max_length=20)),
                ('d1', models.CharField(max_length=5)),
                ('time1', models.CharField(max_length=15)),
                ('starttime1', models.PositiveSmallIntegerField(null=True)),
                ('duration1', models.PositiveSmallIntegerField(null=True)),
                ('delt91', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('d2', models.CharField(max_length=5, null=True)),
                ('time2', models.CharField(max_length=15, null=True)),
                ('starttime2', models.PositiveSmallIntegerField(null=True)),
                ('duration2', models.PositiveSmallIntegerField(null=True)),
                ('delt92', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('loc', models.CharField(blank=True, max_length=10)),
                ('instructor', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal1course1', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c1', to='CourseBrowser.Courses')),
                ('cal1course2', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c2', to='CourseBrowser.Courses')),
                ('cal1course3', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c3', to='CourseBrowser.Courses')),
                ('cal1course4', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c4', to='CourseBrowser.Courses')),
                ('cal1course5', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c5', to='CourseBrowser.Courses')),
                ('cal1course6', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c6', to='CourseBrowser.Courses')),
                ('cal1course7', models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, related_name='c1c7', to='CourseBrowser.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
