# Generated by Django 3.0.5 on 2020-04-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseBrowser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
    ]
