# Generated by Django 3.0.5 on 2020-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseBrowser', '0003_auto_20200415_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='delt91',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='delt92',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
