# Generated by Django 3.0.5 on 2020-04-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseBrowser', '0004_auto_20200415_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cal1course1',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c1', to='CourseBrowser.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course2',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c2', to='CourseBrowser.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course3',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c3', to='CourseBrowser.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course4',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c4', to='CourseBrowser.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course5',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c5', to='CourseBrowser.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course6',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c6', to='CourseBrowser.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course7',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='c1c7', to='CourseBrowser.Courses'),
        ),
    ]
