# Generated by Django 3.0.5 on 2020-04-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseBrowser', '0005_auto_20200418_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cal1course1',
            field=models.CharField(default='blank', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course2',
            field=models.CharField(default='blank', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course3',
            field=models.CharField(default='blank', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course4',
            field=models.CharField(default='blank', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course5',
            field=models.CharField(default='blank', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course6',
            field=models.CharField(default='blank', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal1course7',
            field=models.CharField(default='blank', max_length=12),
        ),
    ]
