# Generated by Django 3.0.8 on 2020-07-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseBrowser', '0006_auto_20200418_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.CharField(default='IN-PERSON', max_length=9),
        ),
    ]
