# Generated by Django 3.0.8 on 2020-07-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseBrowser', '0007_courses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(max_length=9),
        ),
    ]
